### ISSUE TITLE
SinkSelectionsIntoBranchTargets: Crash when cleaning up `Select` instructions

### ISSUE THREAD

**Issue by alessandrogario** [lifting-bits/anvill#148]
Test case: [anvill_issue_148_test_case.json.zip](https://github.com/lifting-bits/anvill/files/6223415/anvill_issue_148_test_case.json.zip)

Found in commit 1ce66508c92ab146b33716f07ef5a151dce458eb

`bool SinkSelectionsIntoBranchTargets::runOnFunction(llvm::Function &func)`

```
  // Clean up the unneeded selects.
  for (auto [sel, br] : select_branches) {
    if (sel->use_empty()) {
      sel->eraseFromParent();
    }
  }
```

**Comment by pgoodman** [comment]
![image](https://user-images.githubusercontent.com/43664/113068538-78056300-918c-11eb-933a-0231a458ffd0.png)
