### ISSUE TITLE
Address of return address was not generated for _start

### ISSUE THREAD

**Issue by pgoodman** [lifting-bits/anvill#250]
The uses of `__anvill_ra` in here should have been lifted to use the return address LLVM intrinsic available on amd64:

```llvm
  %27 = call i32 @__libc_start_main.1(
      i32 (i32, i8**, i8**)* nonnull @main,
      i32 trunc (i64 or (i64 zext (i8 ptrtoint (i8* @__anvill_ra to i8) to i64),
      i64 and (i64 or (i64 or (i64 or (i64 or (i64 shl (i64 zext (i8 trunc (i64 lshr (i64 ptrtoint (i8* @__anvill_ra to i64), i64 32) to i8) to i64), i64 32), i64 or (i64 shl (i64 zext (i8 trunc (i64 lshr (i64 ptrtoint (i8* @__anvill_ra to i64), i64 40) to i8) to i64), i64 40), i64 or (i64 shl (i64 zext (i8 trunc (i64 lshr (i64 ptrtoint (i8* @__anvill_ra to i64), i64 48) to i8) to i64), i64 48), i64 shl (i64 zext (i8 trunc (i64 lshr (i64 ptrtoint (i8* @__anvill_ra to i64), i64 56) to i8) to i64), i64 56)))), i64 shl (i64 zext (i8 trunc (i64 lshr (i64 ptrtoint (i8* @__anvill_ra to i64), i64 24) to i8) to i64), i64 24)), i64 shl (i64 zext (i8 trunc (i64 lshr (i64 ptrtoint (i8* @__anvill_ra to i64), i64 16) to i8) to i64), i64 16)), i64 shl (i64 zext (i8 trunc (i64 lshr (i64 ptrtoint (i8* @__anvill_ra to i64), i64 8) to i8) to i64), i64 8)), i64 -256)) to i32), i8** nonnull %5, i32 (i32, i8**, i8**)* nonnull @init, void ()* nonnull @fini, void ()* %2, i8* nonnull %7)
```

[Archive.zip](https://github.com/lifting-bits/anvill/files/6964001/Archive.zip)

**Comment by pgoodman** [comment]
Also, the `.1` in the function name is not ideal :-/

**Comment by pgoodman** [comment]
The pass that should be responsible for replacing `__anvill_ra` is this one: https://github.com/lifting-bits/anvill/blob/master/libraries/anvill_passes/src/RemoveRemillFunctionReturns.cpp#L170

It's possible that it's not triggering due to a lack of `__remill_function_return` intrinsic calls in `_start`.

**Comment by tetsuo-cpp** [comment]
My understanding is that in the implementation of `_start`, there'd be no `ret` since there's no return address on the stack. Because of that, Remill doesn't emit a call to `__remill_function_return` since that only happens when we encounter some kind of return instruction. That in turn means that the check in `RemoveRemillFunctionReturns` doesn't get triggered and we don't replace `anvill_ra`.

When I turn off all Anvill passes in `Optimize.cpp` and just let it lift each entity with Remill, the emitted IR looks like this which confirms it:
```llvm
; Function Attrs: noinline
define i64 @_start(i64 %0, i64 %1, void ()* %2) #0 {
  %4 = load i64, i64* @__anvill_reg_RAX, align 8
  %5 = load i64, i64* @__anvill_reg_R9, align 8
  %6 = call %struct.Memory* @__remill_write_memory_64(%struct.Memory* null, i64 ptrtoint (i8* @__anvill_sp to i64), i64 ptrtoint (i8* @__anvill_ra to i64))
  %7 = ptrtoint void ()* %2 to i64
  %8 = call void ()* @__anvill_type_hint_Sv(i64 %5)
  %9 = ptrtoint void ()* %8 to i64
  %10 = call void ()* @__anvill_type_hint_Sv(i64 %7)
  %11 = ptrtoint void ()* %10 to i64
  %12 = call void ()* @__anvill_type_hint_Sv(i64 %9)
  %13 = call void ()* @__anvill_type_hint_Sv(i64 %11)
  %14 = ptrtoint void ()* %13 to i64
  %15 = call i64 @__remill_read_memory_64(%struct.Memory* %6, i64 ptrtoint (i8* @__anvill_sp to i64)) #4
  %16 = call i8* @__anvill_type_hint_Sb(i64 %14)
  %17 = ptrtoint i8* %16 to i64
  %18 = call i8* @__anvill_type_hint_Sb(i64 %17)
  %19 = call %struct.Memory* @__remill_write_memory_64(%struct.Memory* %6, i64 add (i64 and (i64 add (i64 ptrtoint (i8* @__anvill_sp to i64), i64 8), i64 -16), i64 -8), i64 %4) #4
  %20 = call %struct.Memory* @__remill_write_memory_64(%struct.Memory* %19, i64 add (i64 and (i64 add (i64 ptrtoint (i8* @__anvill_sp to i64), i64 8), i64 -16), i64 -16), i64 add (i64 an
d (i64 add (i64 ptrtoint (i8* @__anvill_sp to i64), i64 8), i64 -16), i64 -8)) #4
  %21 = call %struct.Memory* @__remill_write_memory_64(%struct.Memory* %20, i64 add (i64 and (i64 add (i64 ptrtoint (i8* @__anvill_sp to i64), i64 8), i64 -16), i64 -24), i64 4208741) #4
  %22 = trunc i64 %15 to i32
  %23 = call i64 @__remill_read_memory_64(%struct.Memory* %21, i64 add (i64 and (i64 add (i64 ptrtoint (i8* @__anvill_sp to i64), i64 8), i64 -16), i64 -16))
  %24 = inttoptr i64 %23 to i8*
  %25 = call i32 @__libc_start_main.1(i32 (i32, i8**, i8**)* nonnull inttoptr (i64 4202320 to i32 (i32, i8**, i8**)*), i32 %22, i8** inttoptr (i64 add (i64 ptrtoint (i8* @__anvill_sp to
i64), i64 8) to i8**), i32 (i32, i8**, i8**)* nonnull inttoptr (i64 4272368 to i32 (i32, i8**, i8**)*), void ()* nonnull inttoptr (i64 4272352 to void ()*), void ()* %13, i8* %24)
  %26 = zext i32 %25 to i64
  %27 = call %struct.Memory* @__remill_error(%struct.State* undef, i64 4208741, %struct.Memory* %21)
  ret i64 %26
}
```

@pgoodman @artemdinaburg 
Now I'm trying to figure out how to fix this but had a question:

Is it valid that there are instructions in `_start` that are referencing `anvill_ra`? There's no return address to "return" to so that doesn't make much sense to me.

**Comment by pgoodman** [comment]
@tetsuo-cpp this is an artifact of our lifting process: we assume all functions that we're lifting have been "called," and therefore have a return address. I presume the kernel doesn't set up a return address on the stack for the ELF entrypoint (`_start`), as then it'd need to go somewhere. I think a good solution would be this:

- [ ] Make sure that Anvill handles functions that don't have returns in them. It is perfectly fine to have functions that do have return addresses, but where all exits are tail-calls.
- [ ] Create a new field in our specification that describes whether or not a function even has a return address.
- [ ] Update the documentation for specifications to describe this new field.
- [ ] Update the binja and ida python scripts to look mark the binary's entrypoint as not having a return address
- [ ] Update the C++ JSON deserialization code to bring the property into C++ land.
- [ ] Update `FunctionDecl` in `include/anvill/Decl.h`
- [ ] Update the `FunctionLifter` in anvill
- [ ] See how the stack frame recovery "reacts" to this new change -- right now that code might rely on the presence of a return address.

**Comment by tetsuo-cpp** [comment]
@pgoodman 
Thanks!

I've had a look and there seems to be an `is_noreturn` field for each function which the IDA and Binja scripts are populating correctly and there is a corresponding member on the `FunctionDecl`. The lifting portion just isn't using this information. So I think I can skip straight to modifying the lifting code to take this into account.

> Make sure that Anvill handles functions that don't have returns in them. It is perfectly fine to have functions that do have return addresses, but where all exits are tail-calls.

How would you typically do this? My current idea is to write a C program and have a function that calls `abort` at the end. Then I'd run the Binja script on it to generate a spec. Then I'd run Anvill over the spec and check for runtime errors + eyeball the IR.

**Comment by pgoodman** [comment]
> I've had a look and there seems to be an is_noreturn field for each function which the IDA and Binja scripts are populating correctly and there is a corresponding member on the FunctionDecl.

`is_noreturn` is more about `[[noreturn]]` or `__attribute__((noreturn))`. This attribute is used on functions like `abort` and such, to say that execution never returns to the caller. A noreturn attribute is different from a function that has no return address.

I would say we want something like `has_return_address`. Another possibility would be that we say the return address type is `v` (`void`), and if that is the case, then there isn't a return address. [Here](https://github.com/lifting-bits/anvill/blob/master/anvill/src/Lifters/FunctionLifter.cpp#L1585-L1592) is where we store the return address, so if we went the type route, then a check could be done on the return address type being `->isVoidTy()`. Would need to update the JSON type deserialization stuff too.

> How would you typically do this? 

https://godbolt.org/z/YGsP3c5rc
