### ISSUE TITLE
Implement optimization pass to remove `__anvill` switch intrinsics

### ISSUE THREAD

**Issue by kumarak** [lifting-bits/anvill#257]
Anvill uses switch intrinsics (`__anvill_complete_switch`/`__anvill_incomplete_switch`) to identify the control flow targets.

The specification recovered by the decompiler includes the possible target list for the indirect jump control flow. The anvill uses the switch intrinsics while lifting to identify the possible target list. The target list could be incomplete if the decompiler fails to recover them from the binaries. The lifter handles the target list as follows: 

- Control flow with single target - No intrinsic, lifted as normal jump
- Control flow with multiple targets, complete: `__anvill_complete_switch` with no default case
- Control flow with single or multiple targets, not complete:  `__anvill_incomplete_switch` with default case making call to `__remill_jump`

The anvill should implement an optimization pass to identify these switch intrinsics and replace them.

**Comment by kumarak** [comment]
Attached specification include function with indirect control flow instruction and the target list. Anvill lift the complete list of targets with switch intrinsics: 
```
...
991:                                              ; preds = %983
  %992 = zext i8 %984 to i32
  %993 = shl nuw nsw i32 %992, 2
  %994 = add i32 %993, add (i32 ptrtoint (i32* @var_835a000_i to i32), i32 -763272)
  %995 = inttoptr i32 %994 to i32*
  %996 = load i32, i32* %995, align 4
  %997 = add i32 %996, ptrtoint (i32* @var_835a000_i to i32)
  %998 = call i32 (i32, ...) @__anvill_complete_switch(i32 %997, i32 134522973, i32 136578775, i32 136578784, i32 136578793, i32 136578809, i32 136578818)
  %999 = add i32 %996, add (i32 ptrtoint (i32* @var_835a000_i to i32), i32 9)
  switch i32 %998, label %1000 [
    i32 0, label %449
    i32 1, label %1001
    i32 2, label %1004
    i32 3, label %1007
    i32 4, label %1010
    i32 5, label %1014
  ]
```

[spec.json.zip](https://github.com/lifting-bits/anvill/files/7162739/spec.json.zip)

**Comment by pgoodman** [comment]
Done in #261.
