### ISSUE TITLE
error linking with doctest lib

### ISSUE THREAD

**Issue by sh4m2hwz** [lifting-bits/anvill#287]
[ 85%] Linking CXX executable test_anvill_passes
/usr/bin/ld: CMakeFiles/test_anvill_passes.dir/src/SwitchLoweringPass.cpp.o: in function `doctest::String doctest::detail::stringifyBinaryExpr<unsigned int, int>(unsigned int const&, char const*, int const&)':
/usr/include/doctest.h:1008: undefined reference to `doctest::String::operator+(doctest::String const&) const'
/usr/bin/ld: /usr/include/doctest.h:1008: undefined reference to `doctest::String::operator+(doctest::String const&) const'
/usr/bin/ld: CMakeFiles/test_anvill_passes.dir/src/SwitchLoweringPass.cpp.o: in function `doctest::String doctest::detail::stringifyBinaryExpr<unsigned long, int>(unsigned long const&, char const*, int const&)':
/usr/include/doctest.h:1008: undefined reference to `doctest::String::operator+(doctest::String const&) const'
/usr/bin/ld: /usr/include/doctest.h:1008: undefined reference to `doctest::String::operator+(doctest::String const&) const'
/usr/bin/ld: CMakeFiles/test_anvill_passes.dir/src/SwitchLoweringPass.cpp.o: in function `doctest::String doctest::detail::stringifyBinaryExpr<llvm::APInt, int>(llvm::APInt const&, char const*, int const&)':
/usr/include/doctest.h:1008: undefined reference to `doctest::String::operator+(doctest::String const&) const'
/usr/bin/ld: CMakeFiles/test_anvill_passes.dir/src/SwitchLoweringPass.cpp.o:/usr/include/doctest.h:1008: more undefined references to `doctest::String::operator+(doctest::String const&) const' follow
/usr/bin/ld: CMakeFiles/test_anvill_passes.dir/src/BranchRecoveryPass.cpp.o: in function `doctest::String doctest::detail::StringMakerBase<true>::convert<llvm::CmpInst::Predicate>(llvm::CmpInst::Predicate const&)':
/usr/include/doctest.h:806: undefined reference to `doctest::detail::getTlsOss()'
/usr/bin/ld: /usr/include/doctest.h:807: undefined reference to `doctest::detail::getTlsOssResult()'
/usr/bin/ld: CMakeFiles/test_anvill_passes.dir/src/BranchRecoveryPass.cpp.o: in function `doctest::String doctest::detail::stringifyBinaryExpr<llvm::CmpInst::Predicate, llvm::CmpInst::Predicate>(llvm::CmpInst::Predicate const&, char const*, llvm::CmpInst::Predicate const&)':
/usr/include/doctest.h:1008: undefined reference to `doctest::String::operator+(doctest::String const&) const'
/usr/bin/ld: CMakeFiles/test_anvill_passes.dir/src/BranchRecoveryPass.cpp.o: in function `doctest::String doctest::detail::StringMakerBase<true>::convert<llvm::CmpInst::Predicate>(llvm::CmpInst::Predicate const&)':
/usr/include/doctest.h:806: undefined reference to `doctest::detail::getTlsOss()'
/usr/bin/ld: /usr/include/doctest.h:807: undefined reference to `doctest::detail::getTlsOssResult()'
/usr/bin/ld: CMakeFiles/test_anvill_passes.dir/src/BranchRecoveryPass.cpp.o: in function `doctest::String doctest::detail::stringifyBinaryExpr<llvm::CmpInst::Predicate, llvm::CmpInst::Predicate>(llvm::CmpInst::Predicate const&, char const*, llvm::CmpInst::Predicate const&)':
/usr/include/doctest.h:1008: undefined reference to `doctest::String::operator+(doctest::String const&) const'
/usr/bin/ld: CMakeFiles/test_anvill_passes.dir/src/BranchRecoveryPass.cpp.o: in function `doctest::String doctest::detail::stringifyBinaryExpr<llvm::Value*, llvm::Argument*>(llvm::Value* const&, char const*, llvm::Argument* const&)':
/usr/include/doctest.h:1008: undefined reference to `doctest::String::operator+(doctest::String const&) const'
/usr/bin/ld: /usr/include/doctest.h:1008: undefined reference to `doctest::String::operator+(doctest::String const&) const'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [anvill/tests/anvill_passes/CMakeFiles/test_anvill_passes.dir/build.make:398: anvill/tests/anvill_passes/test_anvill_passes] Error 1
make[1]: *** [CMakeFiles/Makefile2:496: anvill/tests/anvill_passes/CMakeFiles/test_anvill_passes.dir/all] Error 2

**Comment by sh4m2hwz** [comment]
my actions:
git clone https://github.com/doctest/doctest
cd doctest
mkdir build && cd build
cmake ..
sudo make install
cd ../../
git clone https://github.com/lifting-bits/anvill
cd anvill
mkdir build && cd build
 cmake -DVCPKG_ROOT="../../lifting-bits-downloads/vcpkg_ubuntu-20.04_llvm-12_amd64"  -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ .. 
cmake --build . --target install

**Comment by 2over12** [comment]
Can you try to build anvill with the submoduled version of doctest?
ie. doing `git submodule update --init --recursive` rather than building and installing the latest doctest
