### ISSUE TITLE
Port McSema `XrefFolder` usage for pointers

### ISSUE THREAD

**Issue by surovic** [lifting-bits/anvill#55]
McSema currently contains code for folding and fixing up pointer usage into GEP operations and similar. If anvill has any use fro this it would be great to port it back. Possibly to `Analyze.cpp`. Example:
https://github.com/lifting-bits/mcsema/blob/d9bbd1ea7c31a83d3b201b1c8711675ca7522408/mcsema/BC/Optimize.cpp#L474-L516

**Comment by pgoodman** [comment]
This code has been copied over. Probably needs refactoring and updating, but closing for now.
