### ISSUE TITLE
Hitting "Check failed: dest_size < 64" on binary

### ISSUE THREAD

**Issue by jchv** [lifting-bits/anvill#61]
I'm attempting to run McSema on a reasonably large binary. After a number of hours (about 12 I believe) when using a machine equipped with enough RAM (256 GiB seems to be enough) I finally hit this point:

```
F20201031 04:22:21.503217     6 Analyze.cpp:481] Check failed: dest_size < 64 (64 vs. 64)
*** Check failure stack trace: ***
    @           0x9c6bcc  google::LogMessageFatal::~LogMessageFatal()
    @           0x70d856  anvill::XrefExprFolder::VisitSExt()
    @           0x5f76cb  mcsema::(anonymous namespace)::LowerXrefs()::$_1::operator()()
    @           0x5f2b37  mcsema::(anonymous namespace)::LowerXrefs()
    @           0x5f1ca4  mcsema::OptimizeModule()
    @           0x5ef329  mcsema::LiftCodeIntoModule()
    @           0x6057bc  main
    @     0x7f9be066d0b3  __libc_start_main
    @           0x5b71ae  _start
```

Unfortunately I don't see any other context that might help identify where things ate getting stuck at :)

I used McSema at git master with IDA Pro v7.5.200728 and IDAPython with Python 3 on Windows for flow control reconstruction. I used the latest Docker image of McSema to perform the lifting phase, on a Ubuntu 20.04 VM (An Amazon r5.8xlarge. It OOMs on my local machine with 64 GiB. It also OOMs with 128 GiB of RAM, which is the maximum my local machine is able to handle, so that leaves me in a position of being unable to run locally. Probably will switch to a better CPU platform in the future to reduce runtime though.)

The binary is an x86 Windows binary compiled with Microsoft Visual C++, not obfuscated, and with the accompanied PDB.

It seems like this means that somewhere along the lines an LLVM `sext` instruction is created that attempts to sign-extend an integer, but for some reason a dest size of 64-bit is an error case for this particular code in anvill. Is this a bug, or perhaps missing functionality?

**Comment by pgoodman** [comment]
I believe this is fixes in the master branch now :-)
