### ISSUE TITLE
Remove Python 2.x support

### ISSUE THREAD

**Issue by pgoodman** [lifting-bits/anvill#86]
We're already adding type hints, and the Python 2.7 EOL should mean that we don't even bother trying to run a Python 2 setup.py.

**Comment by surovic** [comment]
Is there any python 2 support besides [CMakeLists.txt](https://github.com/lifting-bits/anvill/blob/master/CMakeLists.txt#L35) ?

**Comment by pgoodman** [comment]
Not anymore. It used to support Python 2, but I think that's been lost since we've started adding type annotations.
